### ISSUE TITLE
Google Play Compliance 

### ISSUE THREAD

**Issue by asd-and-Rizzo** [sergstetsuk/CosyDVR#28]
Google Play Support <googleplay-developer-support+no-reply@google.com>
	
Feb 7 (2 days ago)
	
to me

Hello Google Play Developer,

Our records show that your app, CosyDVR, with package name es.esy.CosyDVR, currently violates our User Data policy regarding Personal and Sensitive Information.

Policy issue: Google Play requires developers to provide a valid privacy policy when the app requests or handles sensitive user or device information. Your app requests sensitive permissions (e.g. camera, microphone, accounts, contacts, or phone) or user data, but does not include a valid privacy policy.

Action required: Include a link to a valid privacy policy on your app's Store Listing page and within your app. You can find more information in our help center.

Alternatively, you may opt-out of this requirement by removing any requests for sensitive permissions or user data.

If you have additional apps in your catalog, please make sure they are compliant with our Prominent Disclosure requirements.

Please resolve this issue by March 15, 2017, or administrative action will be taken to limit the visibility of your app, up to and including removal from the Play Store. Thanks for helping us provide a clear and transparent experience for Google Play users.

Regards,

The Google Play Team

**Comment by sergstetsuk** [comment]
updated https://github.com/sergstetsuk/CosyDVR/blob/master/PRIVACYPOLICY.md
