### ISSUE TITLE
Video flipped on Nexus 5X

### ISSUE THREAD

**Issue by parkerlreed** [sergstetsuk/CosyDVR#32]
5X has an "upside down" sensor which is corrected for in software. This affects a few other phones too.

**Comment by sergstetsuk** [comment]
Did you try reverse landscape option? Does it work?

**Comment by parkerlreed** [comment]
Reverse landscape just sets the screen rotation. Video has the same behavior.

**Comment by sergstetsuk** [comment]
Can you check v1.3.20? In your case you should set "Video Rotation Angle Metadata" to value 180 degrees.

**Comment by sergstetsuk** [comment]
https://app.box.com/s/p8d7ask6zq1ajerbxbji - thtis is not official f-droid release. But only mine debug build. Though it has the same key. And it is much lighter. Don't know why f-droid build is heavier.

**Comment by parkerlreed** [comment]
Sweet! With both of the orientation angles set to 180, it behaves as expected. Thanks!
